services:
  node:
    # Building a custom image described in a docker file.
    build:
      # Setting a context and dockerfile paths allows for Dockerfiles to be stored away in a sub-directory.
      context: ./ # Context of build, this is where the project files are stored.
      dockerfile: ./docker/node.dockerfile # The path to Dockerfile and name of the dockerfile to be built
    # Setting an image name avoids the same image being built multiple times.
    image: csalmeida/shad-react-app:latest
    # Specified the name of the container, commented out to avoid name conflicts when running multiple instances of the image.
    # container_name: protonmail_themes
    ports:
      - 3000:3000
    volumes:
      # Allows changes made to project directory to be accessed by the container via a bind mount.
      - ./:/var/shad-react-app
      # Adds a volume to store node dependencies.
      - /var/shad-react-app/node_modules
